dist: buster

language: python

python:
  - "3.7"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='python3.7-alpine3.8' BUILD_PATH='python3.7-alpine3.8' TEST_STR1='Hello World from Flask in a uWSGI Nginx Docker container with Python 3.7 on Alpine (default)' TEST_STR2='Hello World from Flask in a uWSGI Nginx Docker container with Python 3.7 - testing' RUN_TESTS=''

script:
  - bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
